CREATE OR REPLACE VIEW BOOKING_VIEW AS
SELECT DISTINCT 
         tt.ID,
         sg.DEPARTURE_STATION_ID, 
         sg.ARRIVAL_STATION_ID,
         sg.DISTANCE,
         COMPUTE_DEPARTURE_DATE(tt.ID, sg.DEPARTURE_STATION_ID) DEPARTURE_DATE,
         COMPUTE_ARRIVAL_DATE(tt.ID, sg.ARRIVAL_STATION_ID) ARRIVAL_DATE,
         tt.DEPARTURE_PLATFORM,
         tt.ARRIVAL_PLATFORM,
         rs.ROUTE_ID,
         rs.IS_TERMINAL, 
         tt.TRAIN_ID,
         rs.SEQUENCE_NUMBER
         FROM ROUTES_2_SEGMENTS rs, SEGMENTS sg, TIMETABLE tt
              WHERE rs.SEGMENT_ID = sg.ID
                  AND tt.ROUTE_ID = rs.ROUTE_ID
        ORDER BY rs.ROUTE_ID, rs.SEQUENCE_NUMBER, DEPARTURE_DATE ASC
/
