INSERT INTO TRAINS (ID, CATEGORY, CODE, NOMINAL_SPEED, CARRIAGES) VALUES (TRAINS_SEQ.NEXTVAL, 'Frecciarossa', '9552', 261.00, 10);
INSERT INTO TRAINS (ID, CATEGORY, CODE, NOMINAL_SPEED, CARRIAGES) VALUES (TRAINS_SEQ.NEXTVAL, 'Frecciarossa', '9558', 245.00, 12);
INSERT INTO TRAINS (ID, CATEGORY, CODE, NOMINAL_SPEED, CARRIAGES) VALUES (TRAINS_SEQ.NEXTVAL, 'Frecciarossa 1000', '9654', 265.00, 12);
INSERT INTO TRAINS (ID, CATEGORY, CODE, NOMINAL_SPEED, CARRIAGES) VALUES (TRAINS_SEQ.NEXTVAL, 'Intercity', '702', 199.00, 12);
INSERT INTO TRAINS (ID, CATEGORY, CODE, NOMINAL_SPEED, CARRIAGES) VALUES (TRAINS_SEQ.NEXTVAL, 'Regionale Veloce', '2330', 210.00, 8);
INSERT INTO TRAINS (ID, CATEGORY, CODE, NOMINAL_SPEED, CARRIAGES) VALUES (TRAINS_SEQ.NEXTVAL, 'Intercity notte', '752', 224.00, 12);
INSERT INTO TRAINS (ID, CATEGORY, CODE, NOMINAL_SPEED, CARRIAGES) VALUES (TRAINS_SEQ.NEXTVAL, 'Frecciabianca', '9811', 205.00, 12);
INSERT INTO TRAINS (ID, CATEGORY, CODE, NOMINAL_SPEED, CARRIAGES) VALUES (TRAINS_SEQ.NEXTVAL, 'Frecciargento', '9009', 235.00, 10);
INSERT INTO TRAINS (ID, CATEGORY, CODE, NOMINAL_SPEED, CARRIAGES) VALUES (TRAINS_SEQ.NEXTVAL, 'Frecciargento 1000', '9145', 254.00, 10);
