--------------------------------------------------------------------------------ID,              CATEGORY,     CODE, NOMINAL_SPEED, CARRIAGES
INSERT INTO TRAINS (ID, CATEGORY, CODE, NOMINAL_SPEED, CARRIAGES) VALUES (TRAINS_SEQ.NEXTVAL, 'Frecciarossa', '9552', 289.00, 10);
INSERT INTO TRAINS (ID, CATEGORY, CODE, NOMINAL_SPEED, CARRIAGES) VALUES (TRAINS_SEQ.NEXTVAL, 'Frecciarossa', '9652', 289.00, 11);
INSERT INTO TRAINS (ID, CATEGORY, CODE, NOMINAL_SPEED, CARRIAGES) VALUES (TRAINS_SEQ.NEXTVAL, 'Frecciarossa', '9558', 245.00, 12);
INSERT INTO TRAINS (ID, CATEGORY, CODE, NOMINAL_SPEED, CARRIAGES) VALUES (TRAINS_SEQ.NEXTVAL, 'Frecciarossa 1000', '9654', 245.00, 12);
INSERT INTO TRAINS (ID, CATEGORY, CODE, NOMINAL_SPEED, CARRIAGES) VALUES (TRAINS_SEQ.NEXTVAL, 'Intercity', '702', 199.00, 12);
INSERT INTO TRAINS (ID, CATEGORY, CODE, NOMINAL_SPEED, CARRIAGES) VALUES (TRAINS_SEQ.NEXTVAL, 'Regionale Veloce', '2330', 210.00, 8);
INSERT INTO TRAINS (ID, CATEGORY, CODE, NOMINAL_SPEED, CARRIAGES) VALUES (TRAINS_SEQ.NEXTVAL, 'Intercitynotte', '752', 245.00, 12);
INSERT INTO TRAINS (ID, CATEGORY, CODE, NOMINAL_SPEED, CARRIAGES) VALUES (TRAINS_SEQ.NEXTVAL, 'Frecciabianca', '9811', 205.00, 12);
INSERT INTO TRAINS (ID, CATEGORY, CODE, NOMINAL_SPEED, CARRIAGES) VALUES (TRAINS_SEQ.NEXTVAL, 'Frecciargento', '9009', 235.00, 10);
INSERT INTO TRAINS (ID, CATEGORY, CODE, NOMINAL_SPEED, CARRIAGES) VALUES (TRAINS_SEQ.NEXTVAL, 'Frecciargento 1000', '9145', 295.00, 10);
