--Da Napoli Centrale a Roma Termini e viceversa
INSERT INTO SEGMENTS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (SEGMENTS_SEQ.NEXTVAL, 1, 7, 226.00);
INSERT INTO SEGMENTS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (SEGMENTS_SEQ.NEXTVAL, 7, 1, 226.00);

--Da Napoli Centrale a Bologna Centrale e viceversa
INSERT INTO SEGMENTS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (SEGMENTS_SEQ.NEXTVAL, 1, 10, 573.00);
INSERT INTO SEGMENTS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (SEGMENTS_SEQ.NEXTVAL, 10, 1, 573.00);

--Da Napoli Centrale a Milano Centrale e viceversa
INSERT INTO SEGMENTS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (SEGMENTS_SEQ.NEXTVAL, 1, 15, 836.00);
INSERT INTO SEGMENTS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (SEGMENTS_SEQ.NEXTVAL, 15, 1, 836.00);

--Da Roma Termini a Bologna Centrale e viceversa
INSERT INTO SEGMENTS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (SEGMENTS_SEQ.NEXTVAL, 7, 10, 377.00);
INSERT INTO SEGMENTS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (SEGMENTS_SEQ.NEXTVAL, 10, 7, 377.00);

--Da Roma Termini a Milano Centrale e viceversa
INSERT INTO SEGMENTS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (SEGMENTS_SEQ.NEXTVAL, 7, 15, 571.00);
INSERT INTO SEGMENTS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (SEGMENTS_SEQ.NEXTVAL, 15, 7, 571.00);

--Da Bologna Centrale a Parma e viceversa
INSERT INTO SEGMENTS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (SEGMENTS_SEQ.NEXTVAL, 10, 13, 99.00);
INSERT INTO SEGMENTS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (SEGMENTS_SEQ.NEXTVAL, 13, 10, 99.00);

--Da Parma a Milano Centrale e viceversa
INSERT INTO SEGMENTS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (SEGMENTS_SEQ.NEXTVAL, 13, 15, 128.00);
INSERT INTO SEGMENTS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (SEGMENTS_SEQ.NEXTVAL, 15, 13, 128.00);