--Da Napoli Centrale a Roma Termini
INSERT INTO ROUTE_SEGMENTS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (1, 1, 7, 200.00);

--Da Roma Termini a Milano Centrale
INSERT INTO ROUTE_SEGMENTS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (2, 7, 15, 734.00);

--Da Roma Termini a Bologna
INSERT INTO ROUTE_SEGMENTS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (3, 7, 10, 432.00);

--Da Bologna a Milano
INSERT INTO ROUTE_SEGMENTS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (4, 10, 15, 432.00);