--Da Napoli Centrale a Caserta
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (1, 1, 2, 45.00, NULL);

--Da Caserta a Formia
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (2, 2, 3, 81.00, NULL);

--Da Formia a Latina
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (3, 3, 4, 75.00, NULL);

--Da Latina a Roma Termini
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (4, 4, 5, 73.00, NULL);

--Da Roma Termini a Firenze S. M. Novella
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (5, 5, 6, 287.00, NULL);

--Da Firenze S. M. Novella a Bologna Centrale
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (6, 6, 7, 106.00, NULL);

--Da Bologna Centrale a Modena
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (7, 7, 8, 46.00, NULL);

--Da Modena a Reggio Emilia
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (8, 8, 9, 35.00, NULL);

--Da Reggio Emilia a Parma
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (9, 9, 10, 38.00, NULL);

--Da Parma a Piacenza
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (10, 10, 11, 70.00, NULL);

--Da Piacenza a Milano Centrale
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (11, 11, 12, 68.00, NULL);




--Da Napoli Centrale a Milano Centrale (diretto) no stop
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (12, 1, 12, 837.00, NULL);

--Da Napoli Centrale a Milano Centrale (via Caserta) 1 stop
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (13, 2, 12, 768.00, NULL);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (14, 1, 2, 45.00, 13);

--Da Napoli Centrale a Milano Centrale (via Caserta, Formia) 2 stops
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (15, 3, 12, 685.00, NULL);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (16, 2, 3, 81.00, 15);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (17, 1, 2, 45.00, 16);

--Da Napoli Centrale a Milano Centrale (via Caserta, Formia, Latina) 3 stops
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (18, 4, 12, 610.00, NULL);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (19, 3, 4, 75.00, 18);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (20, 2, 3, 81.00, 19);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (21, 1, 2, 45.00, 20);

--Da Napoli Centrale a Milano Centrale (via Caserta, Formia, Latina, Roma Termini) 4 stops
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (22, 5, 12, 537.00, NULL);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (23, 4, 5, 73.00, 22);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (24, 3, 4, 75.00, 23);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (25, 2, 3, 81.00, 24);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (26, 1, 2, 45.00, 25);

--Da Napoli Centrale a Milano Centrale (via Caserta, Formia, Latina, Roma Termini, Firenze S. M. Novella) 5 stops
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (27, 6, 12, 257.00, NULL);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (28, 5, 6, 287.00, 27);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (29, 4, 5, 73.00, 28);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (30, 3, 4, 75.00, 29);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (31, 2, 3, 81.00, 30);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (32, 1, 2, 45.00, 31);

--Da Napoli Centrale a Milano Centrale (via Caserta, Formia, Latina, Roma Termini, Firenze S. M. Novella, Bologna Centrale) 6 stops
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (33, 7, 12, 151.00, NULL);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (34, 6, 7, 106.00, 33);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (35, 5, 6, 287.00, 34);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (36, 4, 5, 73.00, 35);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (37, 3, 4, 75.00, 36);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (38, 2, 3, 81.00, 37);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (39, 1, 2, 45.00, 38);

--Da Napoli Centrale a Milano Centrale (via Caserta, Formia, Latina, Roma Termini, Firenze S. M. Novella, Bologna Centrale, Modena) 7 stops
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (40, 8, 12, 106.00, NULL);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (41, 7, 8, 46.00, 40);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (42, 6, 7, 106.00, 41);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (43, 5, 6, 287.00, 42);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (44, 4, 5, 73.00, 43);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (45, 3, 4, 75.00, 44);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (46, 2, 3, 81.00, 45);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (47, 1, 2, 45.00, 46);

--Da Napoli Centrale a Milano Centrale (via Caserta, Formia, Latina, Roma Termini, Firenze S. M. Novella, Bologna Centrale, Modena, Reggio Emilia) 8 stops
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (48, 9, 12, 71.00, NULL);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (49, 8, 9, 35.00, 48);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (50, 7, 8, 46.00, 49);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (51, 6, 7, 106.00, 50);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (52, 5, 6, 287.00, 51);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (53, 4, 5, 73.00, 52);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (54, 3, 4, 75.00, 53);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (55, 2, 3, 81.00, 54);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (56, 1, 2, 45.00, 55);

--Da Napoli Centrale a Milano Centrale (via Caserta, Formia, Latina, Roma Termini, Firenze S. M. Novella, Bologna Centrale, Modena, Reggio Emilia, Parma) 9 stops
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (57, 10, 12, 33.00, NULL);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (58, 9, 10, 38.00, 57);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (59, 8, 9, 35.00, 58);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (60, 7, 8, 46.00, 59);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (61, 6, 7, 106.00, 60);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (62, 5, 6, 287.00, 61);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (63, 4, 5, 73.00, 62);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (64, 3, 4, 75.00, 63);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (65, 2, 3, 81.00, 64);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (66, 1, 2, 45.00, 65);

--Da Napoli Centrale a Milano Centrale (via Caserta, Formia, Latina, Roma Termini, Firenze S. M. Novella, Bologna Centrale, Modena, Reggio Emilia, Parma, Piacenza) 10 stops
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (67, 10, 11, 38.00, 11);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (68, 9, 10, 38.00, 67);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (69, 8, 9, 35.00, 68);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (70, 7, 8, 46.00, 69);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (71, 6, 7, 106.00, 70);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (72, 5, 6, 287.00, 71);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (73, 4, 5, 73.00, 72);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (74, 3, 4, 75.00, 73);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (75, 2, 3, 81.00, 74);
INSERT INTO ROUTE_NODES (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE, NEXT_ID) VALUES (76, 1, 2, 45.00, 75);

