INSERT INTO ROUTES (ID, ACTIVE, NAME) VALUES (ROUTES_SEQ.NEXTVAL, 1, 'Tratta 1');

INSERT INTO ROUTES (ID, ACTIVE, NAME) VALUES (ROUTES_SEQ.NEXTVAL, 1, 'Tratta 2');

INSERT INTO ROUTES (ID, ACTIVE, NAME) VALUES (ROUTES_SEQ.NEXTVAL, 1, 'Tratta 3');

INSERT INTO ROUTES (ID, ACTIVE, NAME) VALUES (ROUTES_SEQ.NEXTVAL, 1, 'Tratta 4');

INSERT INTO ROUTES (ID, ACTIVE, NAME) VALUES (ROUTES_SEQ.NEXTVAL, 1, 'Tratta 5');
