INSERT INTO ROUTES (ID, ROUTE_SEGMENT_ID, STOPS_AT_ARRIVAL, NEXT_ID) VALUES (1, 2, 0, NULL);
INSERT INTO ROUTES (ID, ROUTE_SEGMENT_ID, STOPS_AT_ARRIVAL, NEXT_ID) VALUES (2, 1, 1, 1);


INSERT INTO ROUTES (ID, ROUTE_SEGMENT_ID, STOPS_AT_ARRIVAL, NEXT_ID) VALUES (3, 4, 1, NULL);
INSERT INTO ROUTES (ID, ROUTE_SEGMENT_ID, STOPS_AT_ARRIVAL, NEXT_ID) VALUES (4, 3, 0, 3);
INSERT INTO ROUTES (ID, ROUTE_SEGMENT_ID, STOPS_AT_ARRIVAL, NEXT_ID) VALUES (5, 2, 1, 4);