--Tratta 1 (Napoli Centrale - Roma Termini)
INSERT INTO ROUTES_2_SEGMENTS (ROUTE_ID, SEGMENT_ID, PERFORM_STOP, SEQUENCE_NUMBER) VALUES (1, 1, 0, 1);


INSERT INTO ROUTES_2_SEGMENTS (ROUTE_ID, SEGMENT_ID, PERFORM_STOP, SEQUENCE_NUMBER) VALUES (2, 5, 1, 1);
INSERT INTO ROUTES_2_SEGMENTS (ROUTE_ID, SEGMENT_ID, PERFORM_STOP, SEQUENCE_NUMBER) VALUES (2, 4, 0, 2);
INSERT INTO ROUTES_2_SEGMENTS (ROUTE_ID, SEGMENT_ID, PERFORM_STOP, SEQUENCE_NUMBER) VALUES (2, 3, 1, 3);
INSERT INTO ROUTES_2_SEGMENTS (ROUTE_ID, SEGMENT_ID, PERFORM_STOP, SEQUENCE_NUMBER) VALUES (2, 2, 1, 4);
INSERT INTO ROUTES_2_SEGMENTS (ROUTE_ID, SEGMENT_ID, PERFORM_STOP, SEQUENCE_NUMBER) VALUES (2, 1, 1, 5);

INSERT INTO ROUTES_2_SEGMENTS (ROUTE_ID, SEGMENT_ID, PERFORM_STOP, SEQUENCE_NUMBER) VALUES (3, 3, 1, 1);
INSERT INTO ROUTES_2_SEGMENTS (ROUTE_ID, SEGMENT_ID, PERFORM_STOP, SEQUENCE_NUMBER) VALUES (3, 2, 1, 2);
INSERT INTO ROUTES_2_SEGMENTS (ROUTE_ID, SEGMENT_ID, PERFORM_STOP, SEQUENCE_NUMBER) VALUES (3, 1, 1, 3);
