INSERT INTO ROUTES (ID, ROUTE_SEGMENT_ID, STOPS_AT_ARRIVAL, NEXT_ID) VALUES (ROUTES_SEQ.NEXTVAL, 2, 0, NULL);
INSERT INTO ROUTES (ID, ROUTE_SEGMENT_ID, STOPS_AT_ARRIVAL, NEXT_ID) VALUES (ROUTES_SEQ.NEXTVAL, 1, 1, 1);


INSERT INTO ROUTES (ID, ROUTE_SEGMENT_ID, STOPS_AT_ARRIVAL, NEXT_ID) VALUES (ROUTES_SEQ.NEXTVAL, 5, 1, NULL);
INSERT INTO ROUTES (ID, ROUTE_SEGMENT_ID, STOPS_AT_ARRIVAL, NEXT_ID) VALUES (ROUTES_SEQ.NEXTVAL, 4, 0, 3);
INSERT INTO ROUTES (ID, ROUTE_SEGMENT_ID, STOPS_AT_ARRIVAL, NEXT_ID) VALUES (ROUTES_SEQ.NEXTVAL, 3, 1, 4);
INSERT INTO ROUTES (ID, ROUTE_SEGMENT_ID, STOPS_AT_ARRIVAL, NEXT_ID) VALUES (ROUTES_SEQ.NEXTVAL, 2, 1, 5);
INSERT INTO ROUTES (ID, ROUTE_SEGMENT_ID, STOPS_AT_ARRIVAL, NEXT_ID) VALUES (ROUTES_SEQ.NEXTVAL, 1, 1, 6);

INSERT INTO ROUTES (ID, ROUTE_SEGMENT_ID, STOPS_AT_ARRIVAL, NEXT_ID) VALUES (ROUTES_SEQ.NEXTVAL, 4, 1, NULL);
