--Tratta 1 (Napoli Centrale - Roma Termini) diretto
INSERT INTO ROUTES_2_SEGMENTS (ROUTE_ID, SEGMENT_ID, SEQUENCE_NUMBER, IS_TERMINAL) VALUES (1, 1, 1, 1);

--Tratta 2 (Napoli Centrale - Bologna Centrale)
INSERT INTO ROUTES_2_SEGMENTS (ROUTE_ID, SEGMENT_ID, SEQUENCE_NUMBER, IS_TERMINAL) VALUES (2, 1, 1, 0);
INSERT INTO ROUTES_2_SEGMENTS (ROUTE_ID, SEGMENT_ID, SEQUENCE_NUMBER, IS_TERMINAL) VALUES (2, 7, 2, 1);

--Tratta 3 (Bologna Centrale - Milano Centrale)
INSERT INTO ROUTES_2_SEGMENTS (ROUTE_ID, SEGMENT_ID, SEQUENCE_NUMBER, IS_TERMINAL) VALUES (3, 7, 1, 0);
INSERT INTO ROUTES_2_SEGMENTS (ROUTE_ID, SEGMENT_ID, SEQUENCE_NUMBER, IS_TERMINAL) VALUES (3, 11, 2, 0);
INSERT INTO ROUTES_2_SEGMENTS (ROUTE_ID, SEGMENT_ID, SEQUENCE_NUMBER, IS_TERMINAL) VALUES (3, 13, 3, 1);

--Tratta 4 (Napoli Centrale - Milano Centrale) diretto
INSERT INTO ROUTES_2_SEGMENTS (ROUTE_ID, SEGMENT_ID, SEQUENCE_NUMBER, IS_TERMINAL) VALUES (4, 5, 1, 1);

--Tratta 4 (Roma Termini - Milano Centrale) diretto
INSERT INTO ROUTES_2_SEGMENTS (ROUTE_ID, SEGMENT_ID, SEQUENCE_NUMBER, IS_TERMINAL) VALUES (5, 9, 1, 1);