--Tratta 1 (Napoli Centrale - Roma Termini)
INSERT INTO ROUTES_2_SEGMENTS (ROUTE_ID, SEGMENT_ID, SEQUENCE_NUMBER, IS_TERMINAL) VALUES (1, 1, 1, 1);


INSERT INTO ROUTES_2_SEGMENTS (ROUTE_ID, SEGMENT_ID, SEQUENCE_NUMBER, IS_TERMINAL) VALUES (2, 1, 1, 0);
INSERT INTO ROUTES_2_SEGMENTS (ROUTE_ID, SEGMENT_ID, SEQUENCE_NUMBER, IS_TERMINAL) VALUES (2, 2, 2, 0);
INSERT INTO ROUTES_2_SEGMENTS (ROUTE_ID, SEGMENT_ID, SEQUENCE_NUMBER, IS_TERMINAL) VALUES (2, 3, 3, 0);
INSERT INTO ROUTES_2_SEGMENTS (ROUTE_ID, SEGMENT_ID, SEQUENCE_NUMBER, IS_TERMINAL) VALUES (2, 4, 4, 1);

INSERT INTO ROUTES_2_SEGMENTS (ROUTE_ID, SEGMENT_ID, SEQUENCE_NUMBER, IS_TERMINAL) VALUES (3, 3, 1, 0);
INSERT INTO ROUTES_2_SEGMENTS (ROUTE_ID, SEGMENT_ID, SEQUENCE_NUMBER, IS_TERMINAL) VALUES (3, 4, 2, 1);
