--Timetable for sunday, train 1, route 1
--INSERT INTO TIMETABLE (TRAIN_ID, ROUTE_NODE_ID, DEPARTURE_TIME, ARRIVAL_TIME, WEEK_DAY) VALUES (1, 1, TO_TIMESTAMP ('07:12', 'HH24:MI'), TO_TIMESTAMP ('09:12', 'HH24:MI'), 1);
--INSERT INTO TIMETABLE (TRAIN_ID, ROUTE_NODE_ID, DEPARTURE_TIME, ARRIVAL_TIME, WEEK_DAY) VALUES (2, 1, TO_TIMESTAMP ('09:12', 'HH24:MI'), TO_TIMESTAMP ('23:12', 'HH24:MI'), 1);
--INSERT INTO TIMETABLE (TRAIN_ID, ROUTE_NODE_ID, DEPARTURE_TIME, ARRIVAL_TIME, WEEK_DAY) VALUES (2, 2, TO_TIMESTAMP ('19:12', 'HH24:MI'), TO_TIMESTAMP ('13:12', 'HH24:MI'), 1);

--INSERT INTO TIMETABLE (TRAIN_ID, ROUTE_NODE_ID, DEPARTURE_TIME, ARRIVAL_TIME, WEEK_DAY) VALUES (2, 76, TO_TIMESTAMP ('19:12', 'HH24:MI'), TO_TIMESTAMP ('13:12', 'HH24:MI'), 1);
         