INSERT INTO TIMETABLE (ID, TRAIN_ID, ROUTE_ID, SCHEDULED_DATE, DEPARTURE_DATE, ARRIVAL_DATE, DEPARTURE_PLATFORM, ARRIVAL_PLATFORM) VALUES (TIMETABLE_SEQ.NEXTVAL, 1, 1, TO_DATE ('01/01/2019 07:12', 'DD/MM/YYYY HH24:MI'), NULL, NULL, 1, 2);
INSERT INTO TIMETABLE (ID, TRAIN_ID, ROUTE_ID, SCHEDULED_DATE, DEPARTURE_DATE, ARRIVAL_DATE, DEPARTURE_PLATFORM, ARRIVAL_PLATFORM) VALUES (TIMETABLE_SEQ.NEXTVAL, 2, 2, TO_DATE ('01/01/2019 19:12', 'DD/MM/YYYY HH24:MI'), NULL, NULL, 4, 12);
INSERT INTO TIMETABLE (ID, TRAIN_ID, ROUTE_ID, SCHEDULED_DATE, DEPARTURE_DATE, ARRIVAL_DATE, DEPARTURE_PLATFORM, ARRIVAL_PLATFORM) VALUES (TIMETABLE_SEQ.NEXTVAL, 3, 3, TO_DATE ('01/01/2019 20:32', 'DD/MM/YYYY HH24:MI'), NULL, NULL, 14, 21);

INSERT INTO TIMETABLE (ID, TRAIN_ID, ROUTE_ID, SCHEDULED_DATE, DEPARTURE_DATE, ARRIVAL_DATE, DEPARTURE_PLATFORM, ARRIVAL_PLATFORM) VALUES (TIMETABLE_SEQ.NEXTVAL, 8, 4, TO_DATE ('01/01/2019 14:09', 'DD/MM/YYYY HH24:MI'), NULL, NULL, 14, 21);

INSERT INTO TIMETABLE (ID, TRAIN_ID, ROUTE_ID, SCHEDULED_DATE, DEPARTURE_DATE, ARRIVAL_DATE, DEPARTURE_PLATFORM, ARRIVAL_PLATFORM) VALUES (TIMETABLE_SEQ.NEXTVAL, 6, 5, TO_DATE ('01/01/2019 16:29', 'DD/MM/YYYY HH24:MI'), NULL, NULL, 7, 12);

         