--DEPARTURE FROM Napoli Centrale
INSERT INTO ROUTE_DEFINITIONS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (ROUTE_DEFINITIONS_SEQ.NEXTVAL, 1, 2, 29.00);
INSERT INTO ROUTE_DEFINITIONS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (ROUTE_DEFINITIONS_SEQ.NEXTVAL, 1, 3, 45.00);
INSERT INTO ROUTE_DEFINITIONS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (ROUTE_DEFINITIONS_SEQ.NEXTVAL, 1, 4, 52.00);
INSERT INTO ROUTE_DEFINITIONS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (ROUTE_DEFINITIONS_SEQ.NEXTVAL, 1, 5, 215.00);
INSERT INTO ROUTE_DEFINITIONS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (ROUTE_DEFINITIONS_SEQ.NEXTVAL, 1, 6, 154.00);

--DEPARTURE FROM Napoli Afragola
INSERT INTO ROUTE_DEFINITIONS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (ROUTE_DEFINITIONS_SEQ.NEXTVAL, 2, 1, 29.00);
INSERT INTO ROUTE_DEFINITIONS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (ROUTE_DEFINITIONS_SEQ.NEXTVAL, 2, 3, 35.00);
INSERT INTO ROUTE_DEFINITIONS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (ROUTE_DEFINITIONS_SEQ.NEXTVAL, 2, 4, 48.00);
INSERT INTO ROUTE_DEFINITIONS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (ROUTE_DEFINITIONS_SEQ.NEXTVAL, 2, 5, 205.00);
INSERT INTO ROUTE_DEFINITIONS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (ROUTE_DEFINITIONS_SEQ.NEXTVAL, 2, 6, 147.00);

--DEPARTURE FROM Caserta
INSERT INTO ROUTE_DEFINITIONS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (ROUTE_DEFINITIONS_SEQ.NEXTVAL, 3, 1, 45.00);
INSERT INTO ROUTE_DEFINITIONS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (ROUTE_DEFINITIONS_SEQ.NEXTVAL, 3, 2, 35.00);
INSERT INTO ROUTE_DEFINITIONS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (ROUTE_DEFINITIONS_SEQ.NEXTVAL, 3, 4, 18.00);
INSERT INTO ROUTE_DEFINITIONS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (ROUTE_DEFINITIONS_SEQ.NEXTVAL, 3, 5, 205.00);
INSERT INTO ROUTE_DEFINITIONS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (ROUTE_DEFINITIONS_SEQ.NEXTVAL, 3, 6, 147.00);

--DEPARTURE FROM Aversa
INSERT INTO ROUTE_DEFINITIONS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (ROUTE_DEFINITIONS_SEQ.NEXTVAL, 4, 1, 45.00);
INSERT INTO ROUTE_DEFINITIONS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (ROUTE_DEFINITIONS_SEQ.NEXTVAL, 4, 2, 35.00);
INSERT INTO ROUTE_DEFINITIONS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (ROUTE_DEFINITIONS_SEQ.NEXTVAL, 4, 3, 18.00);
INSERT INTO ROUTE_DEFINITIONS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (ROUTE_DEFINITIONS_SEQ.NEXTVAL, 4, 5, 205.00);
INSERT INTO ROUTE_DEFINITIONS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (ROUTE_DEFINITIONS_SEQ.NEXTVAL, 4, 6, 147.00);

--DEPARTURE FROM Roma Termini
INSERT INTO ROUTE_DEFINITIONS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (ROUTE_DEFINITIONS_SEQ.NEXTVAL, 5, 1, 45.00);
INSERT INTO ROUTE_DEFINITIONS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (ROUTE_DEFINITIONS_SEQ.NEXTVAL, 5, 2, 35.00);
INSERT INTO ROUTE_DEFINITIONS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (ROUTE_DEFINITIONS_SEQ.NEXTVAL, 5, 3, 18.00);
INSERT INTO ROUTE_DEFINITIONS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (ROUTE_DEFINITIONS_SEQ.NEXTVAL, 5, 4, 205.00);
INSERT INTO ROUTE_DEFINITIONS (ID, DEPARTURE_STATION_ID, ARRIVAL_STATION_ID, DISTANCE) VALUES (ROUTE_DEFINITIONS_SEQ.NEXTVAL, 5, 6, 67.00);