select * from TIMETABLE

select a.*, LEVEL
  from ROUTE_NODES a--, TIMETABLE t
--  WHERE a.ID = t.ROUTE_NODE_ID
--  START WITH a.DEPARTURE_STATION_ID = 1
  CONNECT BY PRIOR a.NEXT_ID = a.ID
  
SELECT --DEPARTURE_STATION_ID,
MIN(DEPARTURE_STATION_ID) KEEP (DENSE_RANK FIRST ORDER BY a.DEPARTURE_STATION_ID) "Worst",
MAX(DEPARTURE_STATION_ID) KEEP (DENSE_RANK LAST ORDER BY a.DEPARTURE_STATION_ID) "Best"
   FROM ROUTE_NODES a
   CONNECT BY PRIOR a.NEXT_ID = a.ID
 --  GROUP BY a.DEPARTURE_STATION_ID
   
SELECT DISTINCT * from 
(
  select a.DEPARTURE_STATION_ID as DEPARTURE_STATION_ID
    from ROUTE_NODES a
    WHERE LEVEL = 1
    START WITH a.DEPARTURE_STATION_ID = 1
    CONNECT BY PRIOR a.NEXT_ID = a.ID
    ORDER SIBLINGS BY DEPARTURE_STATION_ID
) startStation,
(
  select a.ARRIVAL_STATION_ID as ARRIVAL_STATION_ID, LEVEL
    from ROUTE_NODES a
    WHERE NEXT_ID IS NULL 
    START WITH a.DEPARTURE_STATION_ID = 3
    CONNECT BY a.ID = PRIOR a.NEXT_ID
    ORDER BY LEVEL
) endStation
WHERE startStation



 select DEPARTURE_STATION_ID, a.ARRIVAL_STATION_ID as ARRIVAL_STATION_ID, LEVEL
    from ROUTE_NODES a
    WHERE NEXT_ID IS NULL 
    START WITH a.DEPARTURE_STATION_ID = 3
    CONNECT BY a.ID = PRIOR a.NEXT_ID
    ORDER BY LEVEL