SELECT distinct a.*, LEVEL
      FROM BOOKING_VIEW a
      WHERE a.DEPARTURE_STATION_ID != :arrivalStationId AND a.ARRIVAL_STATION_ID != :departureStationId 
      START WITH a.DEPARTURE_STATION_ID = :departureStationId AND (a.DEPARTURE_DATE BETWEEN :startDate AND :endDate) 
      CONNECT BY NOCYCLE PRIOR a.ARRIVAL_STATION_ID = a.DEPARTURE_STATION_ID 
      AND PRIOR a.ARRIVAL_DATE BETWEEN a.DEPARTURE_DATE - 3/24 AND a.DEPARTURE_DATE 
      ORDER SIBLINGS BY a.ROUTE_ID, a.SEQUENCE_NUMBER, a.DEPARTURE_DATE DESC